### PR TITLE
Implemented access to the relative path property for uploading folders

### PR DESCRIPTION
**Pull request by DouglasDwyer**
I needed folder-uploading support, complete with directory structure, for a separate project.  Since there does not currently appear to be a way to get directory structure, I added the ability to access `webkitRelativePath` from the `IFileInfo` interface, allowing for the support of structured folders to be uploaded using `<input>`.  `IFileInfo.WebkitRelativePath` returns the relative path for any input that is marked `webkitdirectory`, or `null` if the input is not configured to upload folders.

### CODE REVIEW

**Comment by Tewr** [comment]
In principle ok I guess. But I'm not really happy about exposing a non standard property, especially when it has a browser prefix, as it means a future breaking change.

How about a dictionary or and indexer property filled with all the non-standard properties (passing the hasOwnProperty test) of file?

**Comment by DouglasDwyer** [comment]
While I believe the `webkitRelativePath` property is currently implemented across all major WASM-supporting browsers, I understand what you mean.  As such, I've removed the `WebkitRelativePath` property in exchange for the `NonStandardProperties` dictionary.  For any Javascript `File` object, it contains the properties of the `File` prototype not covered by `IFileInfo`.

**Comment by Tewr** [comment]
Great stuff! I'll merge this as soon as I can test it.

**Comment by Tewr** [comment]
This works as expected. Thank you for your contribution.

**Pull request merged**
